id = "red"
name = "Red"
description = "Red support."
version = "0.1.1"
schema_version = 1
authors = [
    "Xie Qingtian <xqtxyz@gmail.com>",
]
repository = "https://github.com/red/zed-red"

[grammars.red]
repository = "https://github.com/red/tree-sitter-red"
commit = "db4d8521c2961a60e48647c9003e1cf53cb388cd"
