name = "Red"
grammar = "red"
path_suffixes = ["red", "reds"]
line_comments = ["; ", ";; ", ";-- "]
first_line_pattern = '^\s*Red(/System)?($|\s)'
autoclose_before = ";:.,=}])>"
word_characters = ["-", "!", "?", "*"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
tab_size = 4
hard_tabs = true
